### ISSUE TITLE
userのuidの設定

### ISSUE THREAD

**Issue by yk-jp** [RecursionCS-Team-Development/Social-Drawing-Guessing-Game-Backend#4]
現在uidの設定が、auto inclementの場合uuidのようなランダムな文字列に変更

**Comment by Takasu-y** [comment]
5回分(user 5人分)のuidを確認してみましたが
MQ -> QQ -> QA -> MTA -> MTEと変化していたので、auto inclementではなさそうです。

uuidのように変更出来るかは調べてみます！

**Comment by yk-jp** [comment]
修正なしで大丈夫そうです！
